import React, { useState, useEffect } from 'react';
import DatePicker from 'react-datepicker';
import 'react-datepicker/dist/react-datepicker.css';
import { Sparkles, Calendar, Info, GitBranch } from 'lucide-react';
import { SUPPORTED_CURRENCIES, getCurrency, BASE_CURRENCY_CODE } from '../../../config/currencies';
import { formatCurrencyCompact, convertToBaseCurrency, getCurrencySymbol, validateDealValue } from '../../../utils/currencyUtils';
import { PIPELINES, getPipeline, stageButtonClasses } from '../../../config/pipelines';
import { DEAL_TYPES } from '../../../config/dealTypes';
import {
  FORECAST_CATEGORIES,
  getForecastCategory,
  getSuggestedForecastCategory,
  forecastChipClasses,
} from '../../../config/forecastCategories';
import { PriceResult, valueMatchesSuggestion } from '../../../utils/productPricingEngine';
import { Tag } from 'lucide-react';

interface DealFormBasicInfoProps {
  formData: any;
  onChange: (field: string, value: any) => void;
  aiSuggestions?: any;
  validationErrors?: Record<string, string>;
  fieldWarnings?: Record<string, string>;
  isNameAutoGenerated?: boolean;
  onRegenerateName?: () => void;
  catalogSuggestion?: PriceResult;
  dealValueUserEdited?: boolean;
  onApplyCatalogPrice?: (amount: number) => void;
}

export const DealFormBasicInfo: React.FC<DealFormBasicInfoProps> = ({
  formData,
  onChange,
  aiSuggestions,
  validationErrors = {},
  fieldWarnings = {},
  isNameAutoGenerated = false,
  onRegenerateName,
  catalogSuggestion,
  dealValueUserEdited = false,
  onApplyCatalogPrice,
}) => {
  const hasNameContext = !!(formData.accountName || formData.product);
  // Derive stages from the selected pipeline — never stale
  const currentPipeline = getPipeline(formData.pipelineId || '');
  const stages = currentPipeline.stages;

  // ── Deal Value display formatting ─────────────────────────────────────────
  // formData.dealValue holds raw digits ("75000"); displayValue shows commas.
  const toDisplay = (raw: any): string => {
    const digits = (raw ?? '').toString().replace(/[^0-9]/g, '');
    return digits ? Number(digits).toLocaleString('en-US') : '';
  };
  const [displayValue, setDisplayValue] = useState(() => toDisplay(formData.dealValue));

  // Sync when the parent changes dealValue externally (AI suggestions, draft
  // restore, catalog price apply) without going through handleValueChange.
  useEffect(() => {
    setDisplayValue(toDisplay(formData.dealValue));
  }, [formData.dealValue]);

  const handleValueChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const digits = e.target.value.replace(/[^0-9]/g, '');
    setDisplayValue(digits ? Number(digits).toLocaleString('en-US') : '');
    onChange('dealValue', digits);
  };

  return (
    <div className="bg-white rounded-xl border border-gray-200 p-6 shadow-sm">
      <div className="flex items-center space-x-3 mb-6 pb-3 border-b border-gray-100">
        <div className="p-2 bg-blue-50 rounded-lg">
          <Info className="h-5 w-5 text-blue-600" />
        </div>
        <div>
          <h2 className="text-base font-semibold text-gray-900">Basic Information</h2>
          <p className="text-xs text-gray-500">Core details about this deal</p>
        </div>
      </div>

      <div className="space-y-6">
        {/* Deal Name */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Deal Name <span className="text-red-500">*</span>
          </label>
          <div className="relative">
            <input
              type="text"
              value={formData.dealName}
              onChange={(e) => onChange('dealName', e.target.value)}
              placeholder={
                hasNameContext
                  ? 'Auto-generating…'
                  : 'e.g., Acme Corp – Enterprise Plan – Jan 2026'
              }
              maxLength={100}
              className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 ${
                validationErrors.dealName
                  ? 'border-red-500 focus:ring-red-500'
                  : isNameAutoGenerated
                  ? 'border-purple-200 focus:ring-purple-400 bg-purple-50/30'
                  : 'border-gray-300 focus:ring-blue-500'
              }`}
            />
            {/* Sparkle badge shown while name is auto-generated */}
            {isNameAutoGenerated && (
              <span className="absolute right-3 top-1/2 -translate-y-1/2 flex items-center space-x-1 text-xs text-purple-500 pointer-events-none">
                <Sparkles className="h-3.5 w-3.5" />
                <span>Auto</span>
              </span>
            )}
          </div>

          {validationErrors.dealName && (
            <p className="mt-1 text-sm text-red-600">{validationErrors.dealName}</p>
          )}

          <div className="flex items-center justify-between mt-1.5">
            <div className="flex items-center space-x-3">
              {/* Auto-generated helper text */}
              {isNameAutoGenerated && (
                <p className="text-xs text-gray-400">
                  Auto-generated from account and product. You can edit anytime.
                </p>
              )}

              {/* Regenerate button — shown when there's context to rebuild from */}
              {hasNameContext && onRegenerateName && (
                <button
                  type="button"
                  onClick={onRegenerateName}
                  className="flex items-center space-x-1 text-xs text-purple-600 hover:text-purple-700 font-medium transition-colors"
                >
                  <Sparkles className="h-3 w-3" />
                  <span>Regenerate</span>
                </button>
              )}
            </div>

            <span className="text-xs text-gray-400 flex-shrink-0">
              {formData.dealName?.length ?? 0}/100
            </span>
          </div>
        </div>

        {/* Deal Value */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Deal Value <span className="text-red-500">*</span>
          </label>
          <div className="flex items-center space-x-2">
            {/* Dynamic currency symbol — updates when currency changes */}
            <span className="text-gray-500 font-medium text-sm w-8 text-center flex-shrink-0">
              {getCurrencySymbol(formData.currency || 'USD')}
            </span>
            <input
              type="text"
              inputMode="numeric"
              value={displayValue}
              onChange={handleValueChange}
              placeholder="50,000"
              className={`flex-1 px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 ${
                validationErrors.dealValue
                  ? 'border-red-500 focus:ring-red-500'
                  : 'border-gray-300 focus:ring-blue-500'
              }`}
            />
            {/* Currency selector built from shared config — add currencies in currencies.ts */}
            <select
              value={formData.currency || 'USD'}
              onChange={(e) => onChange('currency', e.target.value)}
              className="px-3 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-sm"
            >
              {SUPPORTED_CURRENCIES.map((c) => (
                <option key={c.code} value={c.code}>
                  {c.code} — {c.name}
                </option>
              ))}
            </select>
          </div>

          {validationErrors.dealValue && (
            <p className="mt-1 text-sm text-red-600">{validationErrors.dealValue}</p>
          )}

          {/* Base currency conversion hint */}
          {!validationErrors.dealValue && formData.dealValue && formData.currency && formData.currency !== BASE_CURRENCY_CODE && (() => {
            const raw = parseFloat(formData.dealValue.toString().replace(/,/g, ''));
            if (isNaN(raw) || raw <= 0) return null;
            const baseAmt = convertToBaseCurrency(raw, formData.currency);
            return (
              <p className="mt-1.5 text-xs text-gray-500 flex items-center space-x-1">
                <Info className="h-3 w-3 flex-shrink-0" />
                <span>
                  ≈ {formatCurrencyCompact(baseAmt, BASE_CURRENCY_CODE)} {BASE_CURRENCY_CODE} for reporting
                  <span className="text-gray-400 ml-1">(mock rate — live FX coming)</span>
                </span>
              </p>
            );
          })()}

          {/* Catalog price suggestion */}
          {catalogSuggestion?.hasData && !validationErrors.dealValue && (() => {
            const isApplied = valueMatchesSuggestion(formData.dealValue, catalogSuggestion);
            const isOverridden = dealValueUserEdited && formData.dealValue &&
              !isApplied;

            if (isApplied) {
              return (
                <p className="mt-1.5 text-xs text-indigo-600 flex items-center space-x-1">
                  <Tag className="h-3 w-3 flex-shrink-0" />
                  <span>Suggested based on catalog · {catalogSuggestion.basis}</span>
                </p>
              );
            }

            if (isOverridden && onApplyCatalogPrice) {
              return (
                <div className="mt-1.5 flex items-center space-x-2 text-xs text-gray-500">
                  <Tag className="h-3 w-3 text-gray-400 flex-shrink-0" />
                  <span>
                    Catalog suggests{' '}
                    <span className="font-medium text-gray-700">
                      {getCurrencySymbol(formData.currency || 'USD')}{catalogSuggestion.amount.toLocaleString()}
                    </span>
                    {' '}· {catalogSuggestion.basis}
                  </span>
                  <button
                    type="button"
                    onClick={() => onApplyCatalogPrice(catalogSuggestion.amount)}
                    className="text-indigo-600 hover:text-indigo-700 font-medium underline flex-shrink-0"
                  >
                    Apply
                  </button>
                </div>
              );
            }

            return null;
          })()}

          {!catalogSuggestion?.hasData && !validationErrors.dealValue && (!formData.currency || formData.currency === BASE_CURRENCY_CODE) && (
            <p className="mt-1 text-xs text-gray-400">
              Amounts are stored in {getCurrency(formData.currency || BASE_CURRENCY_CODE).name} and used as-is for reporting
            </p>
          )}

          {aiSuggestions && !validationErrors.dealValue && (
            <div className="mt-2 flex items-center space-x-3">
              <div className="flex items-center space-x-1 text-sm text-purple-600">
                <Sparkles className="h-4 w-4" />
                <span>Suggested: {aiSuggestions.valueRange}</span>
              </div>
              <button
                onClick={() => onChange('dealValue', String(aiSuggestions.dealValue))}
                className="px-3 py-1 bg-purple-100 text-purple-700 rounded-lg hover:bg-purple-200 text-sm font-medium transition-colors"
              >
                Apply {formatCurrencyCompact(aiSuggestions.dealValue, formData.currency || 'USD')}
              </button>
            </div>
          )}
        </div>

        {/* Close Date */}
        {(() => {
          // Parse stored YYYY-MM-DD string → Date object for DatePicker
          const selectedDate = formData.closeDate
            ? (() => { const d = new Date(formData.closeDate + 'T12:00:00'); return isNaN(d.getTime()) ? null : d; })()
            : null;

          // Guard: only treat a date as valid when the year is in a sensible range.
          // This prevents partial/junk years (0001, 262026, etc.) from triggering
          // the "past date" reason field or the far-future warning.
          const isValidDate = (d: Date | null): d is Date => {
            if (!d || isNaN(d.getTime())) return false;
            const y = d.getFullYear();
            return y >= 2000 && y <= 2099;
          };

          const today = new Date(); today.setHours(0, 0, 0, 0);
          const isPast = isValidDate(selectedDate) && selectedDate < today;
          const isFarFuture = isValidDate(selectedDate) &&
            selectedDate > new Date(today.getTime() + 365 * 24 * 60 * 60 * 1000);

          const handleDateChange = (date: Date | null) => {
            if (!date) {
              onChange('closeDate', '');
              return;
            }
            const yyyy = date.getFullYear();
            const mm = String(date.getMonth() + 1).padStart(2, '0');
            const dd = String(date.getDate()).padStart(2, '0');
            onChange('closeDate', `${yyyy}-${mm}-${dd}`);
          };

          return (
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Close Date <span className="text-red-500">*</span>
              </label>
              <div className={`relative w-full [&_.react-datepicker-wrapper]:w-full [&_.react-datepicker__input-container]:w-full`}>
                <DatePicker
                  selected={selectedDate}
                  onChange={handleDateChange}
                  dateFormat="dd/MM/yyyy"
                  placeholderText="DD/MM/YYYY"
                  showMonthDropdown
                  showYearDropdown
                  dropdownMode="select"
                  yearDropdownItemNumber={10}
                  scrollableYearDropdown
                  popperPlacement="bottom-start"
                  className={`w-full px-4 py-3 border rounded-lg focus:outline-none focus:ring-2 ${
                    validationErrors.closeDate
                      ? 'border-red-500 focus:ring-red-500'
                      : isPast
                      ? 'border-amber-400 focus:ring-amber-400 bg-amber-50/30'
                      : isFarFuture
                      ? 'border-yellow-400 focus:ring-yellow-400'
                      : 'border-gray-300 focus:ring-blue-500'
                  }`}
                />
                <Calendar className="absolute right-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400 pointer-events-none" />
              </div>

              {/* Hard error */}
              {validationErrors.closeDate && (
                <p className="mt-1 text-sm text-red-600">{validationErrors.closeDate}</p>
              )}

              {/* Past-date warning + reason textarea */}
              {isPast && !validationErrors.closeDate && (
                <div className="mt-2 space-y-2">
                  <div className="flex items-start space-x-2 p-2.5 bg-amber-50 border border-amber-200 rounded-lg">
                    <span className="text-amber-500 text-sm flex-shrink-0">⚠️</span>
                    <div>
                      <p className="text-sm font-medium text-amber-800">Close date is in the past. Allowed for migrations or corrections.</p>
                      <p className="text-xs text-amber-700 mt-0.5">
                        Adding a reason is recommended but not required.
                      </p>
                    </div>
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-amber-800 mb-1">
                      Reason for past close date (recommended)
                    </label>
                    <textarea
                      value={formData.closeDateOverrideReason ?? ''}
                      onChange={(e) => onChange('closeDateOverrideReason', e.target.value)}
                      placeholder="e.g. Migrating deal from previous CRM, late entry after verbal close, admin correction…"
                      rows={2}
                      maxLength={500}
                      className="w-full px-3 py-2 border border-amber-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-amber-400 bg-white resize-none"
                    />
                    <div className="flex justify-between mt-1">
                      <p className="text-xs text-amber-600">Optional — saved with the deal if provided.</p>
                      <span className="text-xs text-gray-400">{(formData.closeDateOverrideReason ?? '').length}/500</span>
                    </div>
                  </div>
                </div>
              )}

              {/* Far-future warning */}
              {isFarFuture && !isPast && !validationErrors.closeDate && (
                <p className="mt-1 text-sm text-yellow-600 flex items-center space-x-1">
                  <span>⚠️</span>
                  <span>This close date is more than 1 year away. Are you sure?</span>
                </p>
              )}

              {/* Default helper text */}
              {!validationErrors.closeDate && !isPast && !isFarFuture && (
                <p className="mt-1 text-xs text-gray-400">
                  Future date recommended. Past dates allowed for migrations or corrections.
                </p>
              )}

              {aiSuggestions && !validationErrors.closeDate && !isPast && (
                <div className="mt-2">
                  <div className="flex items-center space-x-2 text-sm text-purple-600">
                    <Sparkles className="h-4 w-4" />
                    <span>Suggested: {aiSuggestions.closeDays} days from today (Industry avg)</span>
                  </div>
                  <button
                    onClick={() => onChange('closeDate', aiSuggestions.closeDate)}
                    className="mt-2 px-3 py-1.5 bg-purple-100 text-purple-700 rounded-lg hover:bg-purple-200 text-sm font-medium transition-colors"
                  >
                    Apply Suggestion
                  </button>
                </div>
              )}
            </div>
          );
        })()}

        {/* Pipeline selector */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Pipeline <span className="text-red-500">*</span>
          </label>
          <div className="flex items-center space-x-2">
            <div className="p-2 bg-gray-100 rounded-lg flex-shrink-0">
              <GitBranch className="h-4 w-4 text-gray-500" />
            </div>
            <select
              value={formData.pipelineId || ''}
              onChange={(e) => onChange('pipelineId', e.target.value)}
              className="flex-1 px-3 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-sm"
            >
              {PIPELINES.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.name}
                </option>
              ))}
            </select>
          </div>
          <p className="mt-1.5 text-xs text-gray-400">
            {currentPipeline.description} · {stages.length} stages
          </p>
        </div>

        {/* Stage — horizontal bar (stages depend on selected pipeline) */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-3">
            Stage <span className="text-red-500">*</span>
          </label>
          <div className="flex items-center rounded-lg border border-gray-200 overflow-hidden">
            {stages.map((stage, idx) => {
              const isActive = formData.stage === stage.id;
              return (
                <button
                  key={stage.id}
                  type="button"
                  onClick={() => onChange('stage', stage.id)}
                  title={`${stage.probability}% base probability`}
                  className={`flex-1 py-2.5 text-xs font-medium transition-all
                    ${idx !== 0 ? 'border-l border-gray-200' : ''}
                    ${stageButtonClasses(stage, isActive)}`}
                >
                  {stage.name}
                </button>
              );
            })}
          </div>
          <p className="mt-1.5 text-xs text-gray-400">
            Stages shown are specific to the <span className="font-medium text-gray-600">{currentPipeline.name}</span> pipeline
          </p>
        </div>

        {/* Forecast Category */}
        {(() => {
          const currentCategory = formData.forecastCategory || '';
          const suggestedId = getSuggestedForecastCategory(formData.stage || '');
          const suggestedObj = getForecastCategory(suggestedId);
          const isSuggested = currentCategory === suggestedId && !!currentCategory;
          const currentObj = getForecastCategory(currentCategory);

          return (
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="block text-sm font-medium text-gray-700">
                  Forecast Category
                  <span className="ml-1 text-xs text-gray-400 font-normal">(optional)</span>
                </label>
                {isSuggested && currentObj && (
                  <span className={`text-xs px-2 py-0.5 rounded-full border font-medium ${forecastChipClasses(currentObj.chipColor)}`}>
                    Suggested
                  </span>
                )}
              </div>

              <select
                value={currentCategory}
                onChange={(e) => onChange('forecastCategory', e.target.value)}
                className="w-full px-3 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-sm"
              >
                <option value="">— Not set —</option>
                {FORECAST_CATEGORIES.map((cat) => (
                  <option key={cat.id} value={cat.id}>
                    {cat.label}
                  </option>
                ))}
              </select>

              {currentObj && currentCategory && (
                <p className="mt-1 text-xs text-gray-400">{currentObj.description}</p>
              )}

              {!currentCategory && suggestedObj && (
                <p className="mt-1 text-xs text-gray-400">
                  Suggested for {formData.stage ? `this stage: ` : 'this stage: '}
                  <button
                    type="button"
                    onClick={() => onChange('forecastCategory', suggestedId)}
                    className="font-medium text-blue-500 hover:text-blue-600 underline"
                  >
                    {suggestedObj.label}
                  </button>
                </p>
              )}

              <p className="mt-1.5 text-xs text-gray-400">
                Managerial forecast classification; separate from deal stage.
              </p>
            </div>
          );
        })()}

        {/* Deal Type */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Deal Type <span className="text-red-500">*</span>
          </label>
          <select
            value={formData.dealType || ''}
            onChange={(e) => onChange('dealType', e.target.value)}
            className={`w-full px-3 py-2.5 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-sm ${
              !formData.dealType ? 'border-red-300' : 'border-gray-300'
            }`}
          >
            {DEAL_TYPES.map((type) => (
              <option key={type.id} value={type.id}>
                {type.label}
              </option>
            ))}
          </select>
          <p className="mt-1.5 text-xs text-gray-400">
            Used for forecasting, reporting, and commission analysis.
          </p>
        </div>

        {/* Win Probability — compact row with collapsible breakdown */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <label className="text-sm font-medium text-gray-700 flex items-center space-x-1">
              <Sparkles className="h-4 w-4 text-purple-500" />
              <span>Win Probability</span>
              <span className="text-xs text-gray-400 font-normal">(AI-calculated)</span>
            </label>
            <span className="text-lg font-bold text-gray-900">{formData.probability}%</span>
          </div>
          <div className="w-full bg-gray-100 rounded-full h-2">
            <div
              className="bg-gradient-to-r from-blue-500 to-green-500 h-2 rounded-full transition-all duration-300"
              style={{ width: `${formData.probability}%` }}
            />
          </div>
          <div className="mt-2 flex flex-wrap gap-2 text-xs text-gray-500">
            <span className="bg-gray-50 border border-gray-200 rounded px-2 py-0.5">Stage base</span>
            <span className="bg-gray-50 border border-gray-200 rounded px-2 py-0.5">Contact role</span>
            {(formData.source === 'hrms' || formData.hrmsConnection) && (
              <span className="bg-orange-50 border border-orange-200 text-orange-700 rounded px-2 py-0.5">+15% HRMS</span>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
