import { Campaign } from '../types/campaigns';

export const campaignsMockData: Campaign[] = [
  {
    id: 'camp-001',
    name: 'Q1 2025 Cold Outreach',
    description: 'Enterprise SaaS targets',
    status: 'active',
    type: 'email',
    template: 'Cold Outreach',
    leadsCount: 250,
    sendRate: 85,
    sentCount: 213,
    openRate: 35,
    openCount: 74,
    replyRate: 12,
    replyCount: 26,
    conversionRate: 4.0,
    conversionCount: 10,
    createdAt: '2025-01-15',
    owner: 'John Smith',
    tags: ['cold', 'enterprise', 'saas']
  },
  {
    id: 'camp-002',
    name: 'Series A Startup Outreach Campaign',
    description: '',
    status: 'active',
    type: 'multi-channel',
    template: 'Custom',
    leadsCount: 180,
    sendRate: 70,
    sentCount: 126,
    openRate: 12,
    openCount: 15,
    replyRate: 1,
    replyCount: 2,
    conversionRate: 0,
    conversionCount: 0,
    createdAt: '2025-01-10',
    owner: 'Sarah Johnson',
    tags: ['startups', 'series-a']
  },
  {
    id: 'camp-003',
    name: 'HRMS Warm Intro - Tech Hires Q4',
    description: '',
    status: 'paused',
    type: 'email',
    template: 'Warm Intro',
    leadsCount: 45,
    sendRate: 95,
    sentCount: 43,
    openRate: 58,
    openCount: 25,
    replyRate: 22,
    replyCount: 9,
    conversionRate: 8.9,
    conversionCount: 4,
    createdAt: '2025-01-08',
    owner: 'Michael Chen',
    tags: ['warm', 'hrms', 'tech-hires']
  },
  {
    id: 'camp-004',
    name: 'SaaStr Conference Follow-up',
    description: 'Starts: Jan 29, 9am',
    status: 'scheduled',
    type: 'linkedin',
    template: 'Event Follow-up',
    leadsCount: 120,
    sendRate: 0,
    sentCount: 0,
    openRate: 0,
    openCount: 0,
    replyRate: 0,
    replyCount: 0,
    conversionRate: 0,
    conversionCount: 0,
    createdAt: '2025-01-20',
    scheduledFor: '2025-01-29T09:00:00',
    owner: 'Emily Rodriguez',
    tags: ['conference', 'event', 'saastr']
  },
  {
    id: 'camp-005',
    name: 'Re-engagement - Dormant Leads Q4',
    description: 'Not launched yet',
    status: 'draft',
    type: 'multi-channel',
    template: 'Re-engagement',
    leadsCount: 0,
    sendRate: 0,
    sentCount: 0,
    openRate: 0,
    openCount: 0,
    replyRate: 0,
    replyCount: 0,
    conversionRate: 0,
    conversionCount: 0,
    createdAt: '2025-01-22',
    owner: 'David Park',
    tags: ['re-engagement', 'dormant']
  },
  {
    id: 'camp-006',
    name: 'Product Demo Follow-up - Q4 2024',
    description: 'Completed Jan 15',
    status: 'completed',
    type: 'email',
    template: 'Trial Follow-up',
    leadsCount: 500,
    sendRate: 100,
    sentCount: 500,
    openRate: 42,
    openCount: 210,
    replyRate: 15,
    replyCount: 75,
    conversionRate: 6.0,
    conversionCount: 30,
    createdAt: '2024-12-01',
    completedAt: '2025-01-15',
    owner: 'Lisa Anderson',
    tags: ['demo', 'trial', 'follow-up']
  },
  {
    id: 'camp-007',
    name: 'Low-Value Cold Outreach Test',
    description: 'Poor performance',
    status: 'completed',
    type: 'email',
    template: 'Cold Outreach',
    leadsCount: 300,
    sendRate: 95,
    sentCount: 285,
    openRate: 8,
    openCount: 23,
    replyRate: 0.3,
    replyCount: 1,
    conversionRate: 0,
    conversionCount: 0,
    createdAt: '2024-11-15',
    completedAt: '2024-12-15',
    owner: 'Robert Wilson',
    tags: ['test', 'low-value', 'cold']
  },
  {
    id: 'camp-008',
    name: '2024 Annual Retro Campaign',
    description: 'Archived Dec 31',
    status: 'archived',
    type: 'email',
    template: 'Custom',
    leadsCount: 150,
    sendRate: 88,
    sentCount: 132,
    openRate: 18,
    openCount: 24,
    replyRate: 3,
    replyCount: 4,
    conversionRate: 0.7,
    conversionCount: 1,
    createdAt: '2024-10-01',
    archivedAt: '2024-12-31',
    owner: 'Amanda Foster',
    tags: ['retro', 'annual', 'archived']
  },
  {
    id: 'camp-009',
    name: 'LinkedIn Thought Leader Outreach',
    description: '',
    status: 'active',
    type: 'linkedin',
    template: 'Cold Outreach',
    leadsCount: 85,
    sendRate: 90,
    sentCount: 77,
    openRate: 0,
    openCount: 0,
    replyRate: 8,
    replyCount: 6,
    conversionRate: 2.4,
    conversionCount: 2,
    createdAt: '2025-01-05',
    owner: 'Jessica Martinez',
    tags: ['linkedin', 'thought-leader']
  },
  {
    id: 'camp-010',
    name: '⚠️ Urgent: Low Engagement Fix Needed',
    description: '0 opens in 7 days',
    status: 'active',
    type: 'email',
    template: 'Custom',
    leadsCount: 200,
    sendRate: 100,
    sentCount: 200,
    openRate: 5,
    openCount: 10,
    replyRate: 0,
    replyCount: 0,
    conversionRate: 0,
    conversionCount: 0,
    createdAt: '2025-01-18',
    owner: 'Kevin Brown',
    tags: ['urgent', 'low-engagement'],
    notes: 'Need immediate attention - potential deliverability issues'
  }
];

export const campaignTemplates = [
  'Cold Outreach',
  'Warm Intro',
  'Event Follow-up',
  'Trial Follow-up',
  'Re-engagement',
  'Custom'
];
