import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

/**
 * Local-disk file storage for documents.
 *
 * Chosen deliberately over object storage: this deployment is self-hosted, and
 * local disk needs no new infrastructure. The interface here is small on purpose
 * so swapping in S3 later means reimplementing four functions, not touching the
 * controller.
 *
 * THE HAZARDS, AND WHAT IS DONE ABOUT THEM
 *
 * 1. Path traversal. A filename like `../../../../etc/passwd` or one containing
 *    a NUL byte must never influence where bytes land. The stored path is
 *    derived ONLY from the tenant id and a generated uuid — the client filename
 *    is kept as metadata in the database and never touches the filesystem.
 *    resolveKey() additionally re-checks that the final absolute path is inside
 *    the storage root, so a bug upstream still cannot escape.
 *
 * 2. Cross-tenant reads. Files live under a per-tenant directory AND every read
 *    goes through a database lookup scoped to the caller's tenant, so a guessed
 *    key from another tenant resolves to a row the caller cannot see.
 *
 * 3. Stored XSS. An uploaded .html or .svg served inline would execute in the
 *    app's origin. Downloads are always Content-Disposition: attachment with
 *    X-Content-Type-Options: nosniff — see streamHeaders().
 *
 * 4. The storage root is NEVER served statically. There is no express.static
 *    over it; bytes only leave through the authenticated route.
 *
 * 5. Orphans. A failed record insert deletes the file it just wrote, and a
 *    deleted record deletes its file, so disk and database do not drift.
 */

/** Configurable so the root can move (and so tests can use a temp dir). */
const STORAGE_ROOT = path.resolve(
  process.env.FILE_STORAGE_PATH || path.join(__dirname, '../../storage'),
);

/** 25 MB. Large enough for contracts and decks, small enough to bound memory. */
export const MAX_UPLOAD_BYTES = 25 * 1024 * 1024;

export const getStorageRoot = (): string => STORAGE_ROOT;

/**
 * Build the storage key for a new file. The extension is carried over — purely
 * so the file is recognisable on disk during support work — but it is
 * sanitised to a short alphanumeric string first, because it is the only part
 * of this path influenced by client input.
 */
export const buildStorageKey = (tenantId: string, originalName: string): string => {
  const rawExt = path.extname(originalName || '');
  const ext = /^\.[A-Za-z0-9]{1,12}$/.test(rawExt) ? rawExt.toLowerCase() : '';
  // Tenant id comes from a verified JWT and is a uuid, but validate anyway —
  // it is a path segment.
  if (!/^[0-9a-f-]{36}$/i.test(tenantId)) throw new Error('Invalid tenant id');
  return path.posix.join(tenantId, `${crypto.randomUUID()}${ext}`);
};

/**
 * Turn a stored key into an absolute path, refusing anything that escapes the
 * root. Defence in depth: keys are generated by buildStorageKey, but a corrupted
 * or hand-edited database row must not be able to read arbitrary files.
 */
export const resolveKey = (key: string): string => {
  if (!key || key.includes('\0')) throw new Error('Invalid storage key');
  const abs = path.resolve(STORAGE_ROOT, key);
  const rootWithSep = STORAGE_ROOT.endsWith(path.sep) ? STORAGE_ROOT : STORAGE_ROOT + path.sep;
  if (abs !== STORAGE_ROOT && !abs.startsWith(rootWithSep)) {
    throw new Error('Storage key escapes the storage root');
  }
  return abs;
};

export const writeFile = async (key: string, data: Buffer): Promise<{ checksum: string; bytes: number }> => {
  const abs = resolveKey(key);
  await fs.promises.mkdir(path.dirname(abs), { recursive: true });
  // 'wx' fails rather than overwriting: a key collision must be an error, never
  // one document silently replacing another's bytes.
  await fs.promises.writeFile(abs, data, { flag: 'wx', mode: 0o600 });
  return {
    checksum: crypto.createHash('sha256').update(data).digest('hex'),
    bytes: data.byteLength,
  };
};

export const readStream = (key: string): fs.ReadStream => fs.createReadStream(resolveKey(key));

export const statFile = async (key: string): Promise<fs.Stats | null> => {
  try {
    return await fs.promises.stat(resolveKey(key));
  } catch {
    return null;
  }
};

/** Best-effort: a missing file is already the desired end state. */
export const deleteFile = async (key: string): Promise<void> => {
  try {
    await fs.promises.unlink(resolveKey(key));
  } catch (err: any) {
    if (err?.code !== 'ENOENT') throw err;
  }
};

/**
 * Headers for serving a stored file.
 *
 * `attachment` and `nosniff` together are what stop an uploaded .html or .svg
 * from running as script in this origin. The declared content type is echoed
 * only for known-inert types; anything else is served as
 * application/octet-stream rather than trusting a client-supplied MIME type.
 */
const INERT_TYPES = new Set([
  'application/pdf', 'text/plain', 'text/csv',
  'image/png', 'image/jpeg', 'image/gif', 'image/webp',
  'application/msword', 'application/vnd.ms-excel',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation',
]);

export const streamHeaders = (filename: string, declaredType: string | null): Record<string, string> => {
  // RFC 6266: ASCII fallback plus a UTF-8 form, and no quotes/newlines that
  // could break out of the header.
  const safeAscii = (filename || 'download').replace(/[^\x20-\x7E]/g, '_').replace(/["\\\r\n]/g, '_');
  return {
    'Content-Type': declaredType && INERT_TYPES.has(declaredType) ? declaredType : 'application/octet-stream',
    'Content-Disposition':
      `attachment; filename="${safeAscii}"; filename*=UTF-8''${encodeURIComponent(filename || 'download')}`,
    'X-Content-Type-Options': 'nosniff',
    // Belt and braces against any inline rendering path.
    'Content-Security-Policy': "default-src 'none'; sandbox",
    'Cache-Control': 'private, no-store',
  };
};
